# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 412)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 204, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 136, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 204, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 136, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 204, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 247, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 225, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 136, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 102, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 204, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setTextFormat(QtCore.Qt.AutoText)
        self.lblTitle.setScaledContents(True)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.HLConfig_Act = QtWidgets.QHBoxLayout()
        self.HLConfig_Act.setObjectName("HLConfig_Act")
        self.lblHeaderConfig = QtWidgets.QLabel(self.centralwidget)
        self.lblHeaderConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeaderConfig.setObjectName("lblHeaderConfig")
        self.HLConfig_Act.addWidget(self.lblHeaderConfig)
        self.lblConfig_File_Name = QtWidgets.QLabel(self.centralwidget)
        self.lblConfig_File_Name.setText("")
        self.lblConfig_File_Name.setObjectName("lblConfig_File_Name")
        self.HLConfig_Act.addWidget(self.lblConfig_File_Name)
        self.verticalLayout.addLayout(self.HLConfig_Act)
        self.GLConfiguracion = QtWidgets.QGridLayout()
        self.GLConfiguracion.setObjectName("GLConfiguracion")
        self.lblHead_Nombre = QtWidgets.QLabel(self.centralwidget)
        self.lblHead_Nombre.setTextFormat(QtCore.Qt.PlainText)
        self.lblHead_Nombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHead_Nombre.setWordWrap(True)
        self.lblHead_Nombre.setObjectName("lblHead_Nombre")
        self.GLConfiguracion.addWidget(self.lblHead_Nombre, 0, 0, 1, 1)
        self.lblNombre = QtWidgets.QLabel(self.centralwidget)
        self.lblNombre.setText("")
        self.lblNombre.setTextFormat(QtCore.Qt.PlainText)
        self.lblNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNombre.setWordWrap(True)
        self.lblNombre.setObjectName("lblNombre")
        self.GLConfiguracion.addWidget(self.lblNombre, 0, 1, 1, 1)
        self.lblHead_Estados = QtWidgets.QLabel(self.centralwidget)
        self.lblHead_Estados.setTextFormat(QtCore.Qt.PlainText)
        self.lblHead_Estados.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHead_Estados.setWordWrap(True)
        self.lblHead_Estados.setObjectName("lblHead_Estados")
        self.GLConfiguracion.addWidget(self.lblHead_Estados, 0, 2, 1, 1)
        self.lblEstados = QtWidgets.QLabel(self.centralwidget)
        self.lblEstados.setText("")
        self.lblEstados.setTextFormat(QtCore.Qt.PlainText)
        self.lblEstados.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEstados.setWordWrap(True)
        self.lblEstados.setObjectName("lblEstados")
        self.GLConfiguracion.addWidget(self.lblEstados, 0, 4, 1, 1)
        self.lblHead_Alfabeto = QtWidgets.QLabel(self.centralwidget)
        self.lblHead_Alfabeto.setTextFormat(QtCore.Qt.PlainText)
        self.lblHead_Alfabeto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHead_Alfabeto.setWordWrap(True)
        self.lblHead_Alfabeto.setObjectName("lblHead_Alfabeto")
        self.GLConfiguracion.addWidget(self.lblHead_Alfabeto, 1, 0, 1, 1)
        self.lblAlfabeto = QtWidgets.QLabel(self.centralwidget)
        self.lblAlfabeto.setText("")
        self.lblAlfabeto.setTextFormat(QtCore.Qt.PlainText)
        self.lblAlfabeto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlfabeto.setWordWrap(True)
        self.lblAlfabeto.setObjectName("lblAlfabeto")
        self.GLConfiguracion.addWidget(self.lblAlfabeto, 1, 1, 1, 1)
        self.lblHead_Est_Aceptacion = QtWidgets.QLabel(self.centralwidget)
        self.lblHead_Est_Aceptacion.setTextFormat(QtCore.Qt.PlainText)
        self.lblHead_Est_Aceptacion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHead_Est_Aceptacion.setWordWrap(True)
        self.lblHead_Est_Aceptacion.setObjectName("lblHead_Est_Aceptacion")
        self.GLConfiguracion.addWidget(self.lblHead_Est_Aceptacion, 1, 2, 1, 1)
        self.lblEst_Acept = QtWidgets.QLabel(self.centralwidget)
        self.lblEst_Acept.setText("")
        self.lblEst_Acept.setTextFormat(QtCore.Qt.PlainText)
        self.lblEst_Acept.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEst_Acept.setWordWrap(True)
        self.lblEst_Acept.setObjectName("lblEst_Acept")
        self.GLConfiguracion.addWidget(self.lblEst_Acept, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.GLConfiguracion)
        self.HLConfig_Buttons = QtWidgets.QHBoxLayout()
        self.HLConfig_Buttons.setObjectName("HLConfig_Buttons")
        self.btnCreateConfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreateConfig.setObjectName("btnCreateConfig")
        self.HLConfig_Buttons.addWidget(self.btnCreateConfig)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLConfig_Buttons.addItem(spacerItem)
        self.btnLoadConfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadConfig.setFlat(False)
        self.btnLoadConfig.setObjectName("btnLoadConfig")
        self.HLConfig_Buttons.addWidget(self.btnLoadConfig)
        self.verticalLayout.addLayout(self.HLConfig_Buttons)
        self.HLCadena = QtWidgets.QHBoxLayout()
        self.HLCadena.setContentsMargins(8, -1, -1, -1)
        self.HLCadena.setObjectName("HLCadena")
        self.lblHeader_Input = QtWidgets.QLabel(self.centralwidget)
        self.lblHeader_Input.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader_Input.setObjectName("lblHeader_Input")
        self.HLCadena.addWidget(self.lblHeader_Input)
        self.txtInput = QtWidgets.QLineEdit(self.centralwidget)
        self.txtInput.setEnabled(False)
        self.txtInput.setClearButtonEnabled(True)
        self.txtInput.setObjectName("txtInput")
        self.HLCadena.addWidget(self.txtInput)
        self.verticalLayout.addLayout(self.HLCadena)
        self.HLValidate = QtWidgets.QHBoxLayout()
        self.HLValidate.setContentsMargins(-1, -1, 12, -1)
        self.HLValidate.setObjectName("HLValidate")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLValidate.addItem(spacerItem1)
        self.btnValidate = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidate.setEnabled(False)
        self.btnValidate.setObjectName("btnValidate")
        self.HLValidate.addWidget(self.btnValidate)
        self.verticalLayout.addLayout(self.HLValidate)
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout.addWidget(self.lblResult)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lblAuthor = QtWidgets.QLabel(self.centralwidget)
        self.lblAuthor.setObjectName("lblAuthor")
        self.verticalLayout.addWidget(self.lblAuthor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AFD Validator"))
        self.lblTitle.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Bienvenido al AFD Validator V_2.0-Relase. Hecho con mucho ❤️</span></p></body></html>"))
        self.lblHeaderConfig.setText(_translate("MainWindow", "Configuracion Actual:"))
        self.lblHead_Nombre.setText(_translate("MainWindow", "Nombre:"))
        self.lblHead_Estados.setText(_translate("MainWindow", "Estados:"))
        self.lblHead_Alfabeto.setText(_translate("MainWindow", "Alfabeto:"))
        self.lblHead_Est_Aceptacion.setText(_translate("MainWindow", "Estados de aceptacion:"))
        self.btnCreateConfig.setText(_translate("MainWindow", "Crear Configuracion"))
        self.btnLoadConfig.setText(_translate("MainWindow", "Abrir Configuración"))
        self.lblHeader_Input.setText(_translate("MainWindow", "Introduzca la cadena:"))
        self.btnValidate.setText(_translate("MainWindow", "Validar cadena"))
        self.lblResult.setText(_translate("MainWindow", "La cadena es:"))
        self.lblAuthor.setText(_translate("MainWindow", "Hecho por: Rodrigo Alvarez Perez"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

