# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveConfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SaveWindow(object):
    def setupUi(self, SaveWindow):
        SaveWindow.setObjectName("SaveWindow")
        SaveWindow.resize(711, 545)
        SaveWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(SaveWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setStyleSheet("margin:\"4px\";\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(0, 48))
        self.btnCancelar.setBaseSize(QtCore.QSize(0, 0))
        self.btnCancelar.setStyleSheet(";")
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.btnAddConfig = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddConfig.setMinimumSize(QtCore.QSize(0, 48))
        self.btnAddConfig.setBaseSize(QtCore.QSize(0, 0))
        self.btnAddConfig.setStyleSheet("")
        self.btnAddConfig.setObjectName("btnAddConfig")
        self.horizontalLayout.addWidget(self.btnAddConfig)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.txtAlpha = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAlpha.setObjectName("txtAlpha")
        self.gridLayout.addWidget(self.txtAlpha, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtAcept_States = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAcept_States.setObjectName("txtAcept_States")
        self.gridLayout.addWidget(self.txtAcept_States, 2, 3, 1, 1)
        self.txtInit_State = QtWidgets.QLineEdit(self.centralwidget)
        self.txtInit_State.setObjectName("txtInit_State")
        self.gridLayout.addWidget(self.txtInit_State, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.txtStates = QtWidgets.QLineEdit(self.centralwidget)
        self.txtStates.setObjectName("txtStates")
        self.gridLayout.addWidget(self.txtStates, 1, 3, 1, 1)
        self.txtConfig_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.txtConfig_Name.setObjectName("txtConfig_Name")
        self.gridLayout.addWidget(self.txtConfig_Name, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 64))
        self.label_7.setBaseSize(QtCore.QSize(0, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 4)
        self.txtTrans = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtTrans.setMinimumSize(QtCore.QSize(0, 0))
        self.txtTrans.setSizeIncrement(QtCore.QSize(0, 0))
        self.txtTrans.setBaseSize(QtCore.QSize(0, 0))
        self.txtTrans.setObjectName("txtTrans")
        self.gridLayout.addWidget(self.txtTrans, 6, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnImportAFN = QtWidgets.QPushButton(self.centralwidget)
        self.btnImportAFN.setBaseSize(QtCore.QSize(0, 0))
        self.btnImportAFN.setStyleSheet("font-size:14px; \n"
"margin:6px;\n"
"width: 10em;\n"
"height:36px;")
        self.btnImportAFN.setObjectName("btnImportAFN")
        self.horizontalLayout_2.addWidget(self.btnImportAFN)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 4)
        SaveWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SaveWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 22))
        self.menubar.setObjectName("menubar")
        SaveWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SaveWindow)
        self.statusbar.setObjectName("statusbar")
        SaveWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SaveWindow)
        QtCore.QMetaObject.connectSlotsByName(SaveWindow)

    def retranslateUi(self, SaveWindow):
        _translate = QtCore.QCoreApplication.translate
        SaveWindow.setWindowTitle(_translate("SaveWindow", "MainWindow"))
        self.btnCancelar.setText(_translate("SaveWindow", "Cancelar"))
        self.btnAddConfig.setText(_translate("SaveWindow", "Agregar Configuracion"))
        self.label.setText(_translate("SaveWindow", "Nombre de configuracion:"))
        self.label_8.setText(_translate("SaveWindow", "*Nota: Para agregar varios elementos, separe por medio de comas (\",\")"))
        self.label_2.setText(_translate("SaveWindow", "Estados:"))
        self.label_5.setText(_translate("SaveWindow", "Alfabeto:"))
        self.label_3.setText(_translate("SaveWindow", "Estado Inicial:"))
        self.label_4.setText(_translate("SaveWindow", "Estados de aceptacion:"))
        self.label_7.setText(_translate("SaveWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">*Nota: Para agregar una transicion el formato es: </span><span style=\" font-size:14pt; color:#000000;\">estado_previo</span><span style=\" font-size:18pt; color:#000000;\">,</span><span style=\" font-size:14pt; color:#000000;\">valor_cambio</span><span style=\" font-size:18pt; color:#000000;\">,</span><span style=\" font-size:14pt; color:#000000;\">estado_siguiente</span></p><p><span style=\" font-size:14pt; color:#000000;\">Utilice una linea por transicion</span></p></body></html>"))
        self.label_6.setText(_translate("SaveWindow", "Transiciones:"))
        self.btnImportAFN.setText(_translate("SaveWindow", "Importar desde AFN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveWindow = QtWidgets.QMainWindow()
    ui = Ui_SaveWindow()
    ui.setupUi(SaveWindow)
    SaveWindow.show()
    sys.exit(app.exec_())

